### ISSUE TITLE
MaximumLength-rule: null-string causes validation error

### ISSUE THREAD

**Issue by PeterVD-Lansweeper** [Sandra/Sandra.SimpleValidator#6]
Hi,

When using your simple and clean framework, I noticed some strange (to me, that is :-) ) behavior.
If you leave a string field null, the MaximumLength-rule causes a validation error.

Is this intentional? Or should the MaximumLength.IsValid-method be changed to return true?

Kind regards,

Peter

**Comment by PureKrome** [comment]
Quick guess, [this is where it's happening](https://github.com/Sandra/Sandra.SimpleValidator/blob/master/src/Sandra.SimpleValidator/Rules/MinimumLength.cs#L15) in the code ...

**Comment by PeterVD-Lansweeper** [comment]
It's indeed that line, but in MaximumLength.cs. ;-)

In the meantime, I added the code to my project and modified that line.

**Comment by phillip-haydon** [comment]
Hey, I'm just in the middle of moving apartment, I need to update this, it's definitely not intentional.

If you want to fix it for me we accept PRs always :)

**Comment by PeterVD-Lansweeper** [comment]
Massive PR is ready and waiting ;-)

**Comment by phillip-haydon** [comment]
![image](https://user-images.githubusercontent.com/895629/59288568-ac055080-8ca6-11e9-9373-fb0d18abcc49.png)

Should be available sooooon. Let me know if there's any issues. 

Thanks for fixing the issue. I'm crazy bust outside of work at the moment.
